### ISSUE TITLE
windows directory faulty

### ISSUE THREAD

**Issue by MasoodShamsaiee** [connbrack/tbot#1]
the way the directory for browser history works is faulty in windows.
Also, make it not close the browser once the task is canceled.
thanks bye

**Comment by connbrack** [comment]
The browser is intended to not close on cancel; another "enter" key press is required. This is for debugging purposes and allows users to view the browser state if something goes wrong while running.

The browser-data directory is not working for Windows systems. I'll fix this bug shortly.

**Comment by connbrack** [comment]
Fixed with commit: 69aee618e6f341a098de96f07ede59101cbdec16
