### ISSUE TITLE
Like button or Dislike button not found?

### ISSUE THREAD

**Issue by takey1337** [connbrack/tbot#2]
Bot starts. Logins. After nothing happens. Seems like the like dislike button cannot be found?

**Comment by connbrack** [comment]
To confirm, does the like button visually appear on Chrome for you? 

If so, do you know if your error output starts something like this? Note you can change the ```max_wait_for_like_button = 240``` to a smaller number,  or else you will have to wait 4 minutes for this error to appear.

```
looks like you are already logged in!
======== Running, use ctrl+c to quit  ========
Traceback (most recent call last):
  File "/path/to/tbot/app.py", line 49, in <module>
    main()
  File "/path/to/tbot/app.py", line 25, in main
    tbot.wait_for_like_button(max_wait_for_like_button)
  File "/path/to/tbot/app.py", line 44, in wait_for_like_button
    WebDriverWait(self.driver, wait_for_reload_time).until(EC.element_to_be_clickable((By.XPATH, "//button[span/span/span[text()='Like']]")))
```

**Comment by connbrack** [comment]
I'll close this issue for now due to inactivity. If you continue to have this problem, feel free to open a new one.
